[colors.primary]
background = '#120e08'
foreground = '#b3976d'

[colors.normal]
black   = '#120e08'
white   = '#b3976d'
red     = '#b3976d'
green   = '#8c734e'
blue    = '#8c734e'
yellow  = '#b3976d'
cyan    = '#8c734e'
magenta = '#655030'

[colors.bright]
black   = '#231b0e'
white   = '#d1b994'
red     = '#d1b994'
green   = '#b3976d'
blue    = '#b3976d'
yellow  = '#d1b994'
cyan    = '#b3976d'
magenta = '#8c734e'
